// CONSTANTES SESCRITAS EM UPPER CASE SNAKE CASE
// EX: VARIAVEL_EXEMPLO_OK

const FIRST_NAME = 'O VALOR NAO PODE SER MUDADO'

const LAST_NAME;
// LAST_NAME = 'TESTE'
// A ATRIBUICAO SOMENTE PODE SER FEITO
// QUANDO A CONSTANTE É CRIADA
